// https://www.mockapi.io/docs -- here you will find a table, showing you how to use every method (create,post,update,delete)

//1.define a POST request to the server and POST the new expense...
// https://blog.logrocket.com/how-to-make-http-requests-like-a-pro-with-axios/
// go to "how to make an Axios POST request" here to learn some more....
//you can tell you SUCCEEDED if you see the data in the response coming back from the server

//2.nice! now give a little user feedback to the user so he can know he succeeded. also, clear the numbers in the textField...

//3.now, make a NEW page, that shows all of the expenses using a GET request. parse the JSON and render it on the screen beautifully...

//4.cool. now, do a DELETE button near every row of expense. and let the user DELETE an expense if he wants to hide from his bney garin.
